global vs per site preference
ansh/jiffyreader.com pull request #111
Opened 2022-06-01 20:20 UTC by jhonalino

implementation is not yet complete. just creating a pull request for initial GUI showcase. 

<img width="165" alt="image" src="https://user-images.githubusercontent.com/13143458/171493922-41664490-6c8a-4ff5-bfbb-df9574034d73.png">

2022-06-01 20:27 UTC, jhonalino commented
<img width="206" alt="image" src="https://user-images.githubusercontent.com/13143458/171495375-3d83448f-8743-4909-81ce-870358c458c0.png">

2022-06-01 22:43 UTC, ansh commented
@jhonalino This looks quite good! Great job so far.

2022-06-01 23:14 UTC, Explosion-Scratch requested changes
Maybe we could incorporate these styles as well?
- Hover + Focus shadow on buttons
- Less dramatic scale effect
- `accent-color` for inputs
- Better font, dark gray now with a light font-weight, slightly larger

2022-06-01 23:14 UTC, Explosion-Scratch commented on src/style.css
> +  box-sizing: border-box;
```suggestion
  box-sizing: border-box;
  transition-property: background-color, transform, box-shadow;
  transition-duration: 200ms;
```

2022-06-01 23:14 UTC, Explosion-Scratch commented on src/style.css
```suggestion
button:hover, button:focus {
  box-shadow: 0 0 0 3px #3aa75733;
}
```

2022-06-01 23:14 UTC, Explosion-Scratch commented on src/style.css
> +    Ubuntu, Cantarell, Helvetica Neue, sans-serif;
```suggestion
    Ubuntu, Cantarell, Helvetica Neue, sans-serif;
  font-weight: 200;
  color: #666;
  font-size: 1.3rem;
  accent-color: #2a8241;
```

2022-06-01 23:14 UTC, Explosion-Scratch commented on src/style.css
> +  transform: scale(1.05);
1.05 looks a bit dramatic
```suggestion
  transform: scale(1.02);
```

2022-06-02 08:21 UTC, jhonalino commented
Implementation + demo
https://user-images.githubusercontent.com/13143458/171586678-a79460d4-da0b-4541-a0df-bc12af4d1169.mp4
would highly appreciate feedback. thank you very much. one last thing I need to implement is the "run on pageload" but it feels like I would have to duplicate bunch of code between content and popup scripts. any idea how to go about it a cleaner way?

2022-06-02 19:51 UTC, asieduernest12 commented
i like this too looks great. will take some time to look through but i dont see anything wrong yet. will give more feedback after looking through.

2022-06-03 03:00 UTC, jhonalino commented
implemented the page load setting
<img width="158" alt="image" src="https://user-images.githubusercontent.com/13143458/171778050-4b8b460b-62be-4dc0-b4e4-5ca555e4496f.png">

2022-06-03 07:55 UTC, jhonalino commented
updated the lineheight logic so data is set from prefs -> view instead of view->prefs->view it should still function the same.

and with that update, the new ContentScript preferences logic now looks like this: 
which has access to all the preferences including the onPageLoad on subscribe 
PopupScript is using this same init API to subscribe to preference too

`  const { start } = Preferences.init({
    getOrigin: async () => new Promise((resolve, _) => {
      resolve(window.location.origin);
    }),
    subscribe: (prefs) => {
      if (!prefs.onPageLoad) {
        return;
      }
      setSaccadesIntervalInDOM(prefs.saccadesInterval);
      setReadingMode(prefs.enabled);
      setFixationStrength(prefs.fixationStrength);
      setLineHeight(prefs.lineHeight);
    },
  });
` 

and with this update. I believe this pull request implementation is complete. Looking forward for your feedback. thank you very much!

2022-06-03 08:40 UTC, asieduernest12 reviewed
looks really impressive some comments here and there expecially summarizing the logic would go a long way to help anyone understand whats going on here without looking at the code so hard my screen feels offended. but i really like this. nice work... high five

2022-06-03 09:53 UTC, jhonalino commented
> looks really impressive. some comments here and there mosly summarizing the logic would go a long way to help anyone understand whats going on here (preferences/index.js) without looking at the code so hard my screen feels offended.
> 
> but i really like this. nice work... high five

high five!
thank you so much for the feedback! I've added comments all the functions for preferences/index.js. please do let me know if those comments do provide clarity or if its still missing some explanations to help anyone understand what's going on 

>  without looking at the code so hard my screen feels offended.
> 
hahaha my bad !

2022-06-04 01:03 UTC, asieduernest12 commented
other issues
[on pageload not acting as expected](https://youtu.be/eytJIQJTBkI)

[default fixations](https://youtu.be/sKHQAH7iM3k)

[site preferences proposal](https://youtu.be/liJCXGBMmpA)

2022-06-04 01:03 UTC, asieduernest12 requested changes

2022-06-04 01:29 UTC, Explosion-Scratch commented
> 

You know you can just drag + drop the MP4 files onto an issue comment right?

2022-06-04 01:44 UTC, jhonalino commented
> other issues in video form
> 
> [on pageload not acting as expected](https://youtu.be/eytJIQJTBkI)
> 
> [default fixations](https://youtu.be/sKHQAH7iM3k)
> 
> [site preferences proposal](https://youtu.be/liJCXGBMmpA)

@asieduernest12 you're the best! I highly appreciate these videos feedback. I've committed updates to address the first 2 issue.  
1 [on pageload not acting as expected](https://youtu.be/eytJIQJTBkI)

2 [default fixations](https://youtu.be/sKHQAH7iM3k)

and will work on the third one next.

2022-06-04 02:26 UTC, asieduernest12 commented
awesome awesome 
so i think there is one more buggy behaviour with the reading mode toggle
[toggle buggy behaviour video](https://youtu.be/DdvnQmN40vE)

it is also present when you use the site preferences

2022-06-04 02:31 UTC, Explosion-Scratch commented
> [toggle buggy behaviour video](https://youtu.be/DdvnQmN40vE)

That sounds like a mix of an autogenerated title and a tongue twister

2022-06-04 02:33 UTC, asieduernest12 commented
> > 
> 
> You know you can just drag + drop the MP4 files onto an issue comment right?

the videos must be under 10mb to be added to a comment, the earlier videos were above the limit

2022-06-04 02:35 UTC, Explosion-Scratch commented
> > > 
> > 
> > 
> > You know you can just drag + drop the MP4 files onto an issue comment right?
> 
> the videos must be under 10mb to be added to a comment, the earlier videos were above the limit

My screen recorder produces massive files even though my screen resolution is not incredible and simply converting them to MP4 and increasing the speed 2x really compresses them (like 80%)

2022-06-04 02:35 UTC, asieduernest12 commented
> > [toggle buggy behaviour video](https://youtu.be/DdvnQmN40vE)
> 
> That sounds like a mix of an autogenerated title and a tongue twister
![HappyBabyLaughingGIF](https://user-images.githubusercontent.com/20851930/171975008-304628a4-18f1-43a2-9fbb-3575f5bf9cff.gif)

2022-06-04 02:46 UTC, asieduernest12 commented
> > > > 
> > > 
> > > 
> > > You know you can just drag + drop the MP4 files onto an issue comment right?
> > 
> > 
> > the videos must be under 10mb to be added to a comment, the earlier videos were above the limit
> 
> My screen recorder produces massive files even though my screen resolution is not incredible and simply converting them to MP4 and increasing the speed 2x really compresses them (like 80%)



> > > > 
> > > 
> > > 
> > > You know you can just drag + drop the MP4 files onto an issue comment right?
> > 
> > 
> > the videos must be under 10mb to be added to a comment, the earlier videos were above the limit
> 
> My screen recorder produces massive files even though my screen resolution is not incredible and simply converting them to MP4 and increasing the speed 2x really compresses them (like 80%)

yeah the speed up trick works magic but i cant do that since i was talking in the video. speeding it up would just turn me into a horrible tongue twister rambling

2022-06-04 03:25 UTC, jhonalino commented
> awesome awesome so i think there is one more buggy behaviour with the reading mode toggle [toggle buggy behaviour video](https://youtu.be/DdvnQmN40vE)
> 
> it is also present when you use the site preferences

thank you so much for the video! I've published an update to address this issue. 
I removed that reading mode state from preferences but keep its initiate state sync only if page load is true. so if its starts out toggled via page load. it will be highlighted but after that. it can be toggled on and off without affecting page load button highlight and vice versa.  

please lmk if still causing an issue for you? thank you very much! I will continue on the [site preferences proposal](https://youtu.be/liJCXGBMmpA) next

2022-06-04 03:52 UTC, asieduernest12 commented
i think everything checks out.. thank you so much @jhonalino your code is real elegant.

2022-06-04 04:48 UTC, jhonalino commented
@asieduernest12 I believe I got [site preferences proposal](https://youtu.be/liJCXGBMmpA) working. do you mind testing it to see if I got it right or if I'm missing something? thank you very much! highly appreciate your feedback @asieduernest12

2022-06-04 05:05 UTC, jhonalino reviewed
added parsenode back outside the bolded element check @asieduernest12 sorry about that. I thought I needed to protect that from double parsing, turns out we already have ignore logic for double parsing! thank you very much!

2022-06-04 06:05 UTC, merged

2022-06-04 13:28 UTC, Explosion-Scratch commented
![Cool gif](https://media3.giphy.com/media/cFkiFMDg3iFoI/giphy.gif?cid=93787727432c75gnbaymq1ha37eikm8p3dya3p4xpb7380uk&rid=giphy.gif&ct=g)